# Generated by Django 4.2.11 on 2025-03-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpmanager', '0002_questionpaper_subject_code_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='qpmanager.department')),
            ],
            options={
                'verbose_name_plural': 'Schemes',
                'ordering': ['-year'],
                'unique_together': {('year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester')])),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='qpmanager.scheme')),
            ],
            options={
                'verbose_name_plural': 'Semesters',
                'ordering': ['number'],
                'unique_together': {('number', 'scheme')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='qpmanager.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'semester')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
